services:
  golang:
    container_name: golang
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ponegraph-net
    environment:
      - GRAPHDB_URL=http://graphdb:7200/repositories/ponegraph-music
    depends_on:
      init_graphdb:
        condition: service_completed_successfully

  init_graphdb:
    container_name: init_graphdb
    image: alpine/curl
    depends_on:
      graphdb:
        condition: service_healthy
    volumes:
      - ./data:/data
      - ./init_graphdb.sh:/init_graphdb.sh:ro
    entrypoint: ["/bin/sh", "/init_graphdb.sh"]
    networks:
      - ponegraph-net

  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.6.4
    ports:
      - "7200:7200"
    volumes:
      - ./data:/data
      - ./graphdb:/opt/graphdb/home
    environment:
      - JVM_OPTS=-Xmx8g
      - GRAPHDB_HOME=/opt/graphdb/home
      - GRAPHDB_CONNECTORS_ENABLE=*
      - GRAPHDB_WORKBENCH_ENABLED=true
    networks:
      - ponegraph-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200/rest/repositories"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  ponegraph-net:
    driver: bridge
